#!/usr/bin/env python3
"""Paired-seed statistics underlying main-text Fig. 4.

This script intentionally accepts only the twelve 100-ms summaries generated by
``run_promoted_povm_ensemble.py``.  In particular, it never searches the legacy
or modular result trees.  Each accepted summary must contain the three receiver
strategies evaluated with common noise draws:

* ``edge_uniform``;
* ``optimal_singlecopy``;
* ``promoted_singlecopy``.

The phase data live only in the C=10 closure subspace, while the amplitude data
remain in the complete E=15 edge space.  The promoted result is selected by the
configured finite-copy receiver cache, which may also retain the QLAN
covariance as an asymptotic reference.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
BLOCK_SIZE = int(os.environ.get("FIG2_STATS_COHERENT_BLOCK_SIZE", "3"))
RUN_SUFFIX = os.environ.get(
    "FIG2_STATS_RUN_SUFFIX",
    f"ns{BLOCK_SIZE}_eff002_perband_localclosure_nogauge_nocoreprior_chi0p85w075to100",
).strip()
DEFAULT_RUN_ROOT = (
    ROOT / "results_12seed_raw" / "100ms"
)
DEFAULT_RESULT_DIR = ROOT / "results"
DEFAULT_FIGURE_DIR = ROOT / "figures"
DEFAULT_STEM = f"sm_paired_povm_100ms_{RUN_SUFFIX}"
DEFAULT_RECEIVER_CACHE = Path(
    os.environ.get(
        "FIG2_STATS_RECEIVER_CACHE",
        str(ROOT / "receiver_cache_eff002_remote6_finite_perband_100ms_ns3_v1.npz"),
    )
)

SEEDS = tuple(range(20260529, 20260541))
METRICS = ("blr_corr", "global_corr")
CHI2_METRICS = ("amp_chi2", "phase_chi2")
METRIC_LABELS = {
    "blr_corr": "BLR correlation",
    "global_corr": "All-pixel correlation",
}
PROMOTION_MODEL = os.environ.get(
    "FIG2_STATS_PROMOTION_MODEL", "finite_ns3_povm_q2_per_band_near_transit"
).strip()
FINITE_NS_QLAN_FISHER_FACTOR = float(
    os.environ.get("FIG2_STATS_FINITE_NS_QLAN_FISHER_FACTOR", "1.0")
)
BOOTSTRAP_SEED = 20260713
DEFAULT_BOOTSTRAP_RESAMPLES = 50_000
N_EDGE = 15
LOOP_LABELS = (
    "1-2-3",
    "1-2-4",
    "1-2-5",
    "1-3-4",
    "1-3-6",
    "2-4-5",
    "2-5-6",
    "3-4-6",
    "3-5-6",
    "4-5-6",
)


@dataclass(frozen=True)
class Strategy:
    key: str
    short_label: str
    plot_label: str
    color: str


@dataclass(frozen=True)
class Comparison:
    key: str
    label: str
    minuend: str
    subtrahend: str


STRATEGIES = (
    Strategy("edge_uniform", "Uniform edge-first", "Uniform\nedge-first", "#0077b6"),
    Strategy(
        "optimal_singlecopy",
        "Optimal single-copy POVM",
        "Optimal\nsingle-copy POVM",
        "#0a9396",
    ),
    Strategy(
        "promoted_singlecopy",
        f"Induced joint POVM (n_s={BLOCK_SIZE})",
        f"Joint POVM\n$n_s={BLOCK_SIZE}$",
        "#9d0208",
    ),
)
QLAN_COLOR = "#6a4c93"
COMPARISONS = (
    Comparison(
        "optimal_minus_edge",
        "optimal single-copy minus uniform edge-first",
        "optimal_singlecopy",
        "edge_uniform",
    ),
    Comparison(
        "promoted_minus_single",
        "joint POVM minus optimal single-copy",
        "promoted_singlecopy",
        "optimal_singlecopy",
    ),
    Comparison(
        "promoted_minus_edge",
        "joint POVM minus uniform edge-first",
        "promoted_singlecopy",
        "edge_uniform",
    ),
)
STRATEGY_BY_KEY = {item.key: item for item in STRATEGIES}


class InputValidationError(RuntimeError):
    """Raised when a summary is not from the required paired ensemble."""


def summary_path(run_root: Path, seed: int) -> Path:
    run_tag = f"paired_povm_100ms_seed{seed}_{RUN_SUFFIX}"
    stem = f"broad_plume_split_objective_nmode_rml_{run_tag}_summary.json"
    return run_root / f"seed_{seed}" / "rml_outputs" / stem


def _require(condition: bool, path: Path, message: str) -> None:
    if not condition:
        raise InputValidationError(f"Invalid paired summary {path}: {message}")


def _as_finite_float(value: Any, *, path: Path, field: str) -> float:
    try:
        result = float(value)
    except (TypeError, ValueError) as exc:
        raise InputValidationError(
            f"Invalid paired summary {path}: {field} is not numeric"
        ) from exc
    if not math.isfinite(result):
        raise InputValidationError(
            f"Invalid paired summary {path}: {field} is not finite"
        )
    return result


def _validate_summary(path: Path, seed: int) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    try:
        payload = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise InputValidationError(f"Malformed JSON in {path}: {exc}") from exc

    stats = payload.get("stats")
    _require(isinstance(stats, dict), path, "missing object 'stats'")
    assert isinstance(stats, dict)
    expected_keys = {item.key for item in STRATEGIES}

    rows = payload.get("rows")
    _require(isinstance(rows, list), path, "missing list 'rows'")
    assert isinstance(rows, list)
    row_keys = [row.get("strategy") for row in rows if isinstance(row, dict)]
    _require(
        len(rows) == len(STRATEGIES) and set(row_keys) == expected_keys and len(set(row_keys)) == len(row_keys),
        path,
        f"expected exactly {sorted(expected_keys)}, found {row_keys}",
    )

    _require(int(stats.get("n_station", -1)) == 6, path, "n_station must be 6")
    _require(
        int(stats.get("n_edge_amplitude", -1)) == 15,
        path,
        "amplitude data must span the full E=15 edge space",
    )
    _require(
        int(stats.get("n_closure_phase", -1)) == 10,
        path,
        "phase data must span only the C=10 closure subspace",
    )
    _require(
        stats.get("phase_parameter_space") == "closure subspace only",
        path,
        "phase_parameter_space must be 'closure subspace only'",
    )
    _require(
        str(stats.get("closure_data_representation", "")).startswith(
            "real-valued local closure coordinates"
        ),
        path,
        "closure data must retain the locally unwrapped POVM coordinates",
    )
    _require(
        stats.get("amplitude_parameter_space") == "complete E-dimensional edge space",
        path,
        "amplitude_parameter_space must be 'complete E-dimensional edge space'",
    )
    _require(
        stats.get("promotion_model") == PROMOTION_MODEL,
        path,
        f"promotion_model must be {PROMOTION_MODEL!r}",
    )
    _require(
        int(stats.get("coherent_block_size", -1)) == BLOCK_SIZE,
        path,
        f"coherent_block_size must be n_s={BLOCK_SIZE}",
    )
    _require(
        abs(
            float(stats.get("finite_ns_qlan_fisher_factor", 1.0))
            - FINITE_NS_QLAN_FISHER_FACTOR
        )
        <= 1.0e-12,
        path,
        "finite_ns_qlan_fisher_factor does not match the requested ensemble",
    )
    _require(stats.get("paired_noise_draws") is True, path, "paired_noise_draws must be true")
    _require(
        abs(float(stats.get("existing_coupled_area_fraction", -1.0)) - 1.0) <= 1.0e-12,
        path,
        "existing-station coupled area fraction must equal 1",
    )
    _require(
        abs(float(stats.get("remote_diameter_m", -1.0)) - 6.0) <= 1.0e-12,
        path,
        "remote-station diameter must equal 6 m",
    )
    _require(
        abs(float(stats.get("photon_collection_efficiency", -1.0)) - 0.02) <= 1.0e-12,
        path,
        "photon collection efficiency must equal 0.02",
    )
    for branch in ("amplitude_branch_fraction", "phase_branch_fraction"):
        value = _as_finite_float(stats.get(branch), path=path, field=f"stats.{branch}")
        _require(abs(value - 0.5) <= 1.0e-12, path, f"{branch} must equal 0.5")

    stress = stats.get("sample_stress_test")
    _require(isinstance(stress, dict), path, "missing stats.sample_stress_test")
    assert isinstance(stress, dict)
    exposure = _as_finite_float(
        stress.get("effective_exposure_s"),
        path=path,
        field="stats.sample_stress_test.effective_exposure_s",
    )
    _require(abs(exposure - 0.100) <= 1.0e-12, path, "effective exposure must be 100 ms")
    _require(
        int(stress.get("rng_seed", -1)) == seed,
        path,
        f"stored rng_seed must equal directory seed {seed}",
    )
    _require(
        stress.get("run_tag") == f"paired_povm_100ms_seed{seed}_{RUN_SUFFIX}",
        path,
        "run_tag does not match the required paired 100-ms ensemble",
    )
    fixed_settings = {
        "rml_prior_weight": 0.01,
        "rml_tv_weight": 0.01,
        "rml_entropy_weight": 0.005,
        "rml_amp_chi2_target": 0.85,
        "rml_amp_chi2_min": 0.75,
        "rml_amp_chi2_max": 1.00,
        "rml_phase_chi2_target": 0.85,
        "rml_phase_chi2_min": 0.75,
        "rml_phase_chi2_max": 1.00,
    }
    for key, expected in fixed_settings.items():
        value = _as_finite_float(
            stress.get(key), path=path, field=f"stats.sample_stress_test.{key}"
        )
        _require(
            abs(value - expected) <= 1.0e-12,
            path,
            f"{key} must equal the common value {expected}",
        )
    _require(
        stress.get("rml_morphology_specific_core_prior") == "none",
        path,
        "no morphology-specific single-core prior may be present",
    )

    clean_rows: list[dict[str, Any]] = []
    for row in rows:
        assert isinstance(row, dict)
        strategy = str(row["strategy"])
        clean: dict[str, Any] = {
            "seed": seed,
            "strategy": strategy,
            "label": STRATEGY_BY_KEY[strategy].short_label,
            "exposure_s": exposure,
            "phase_space": "closure",
            "phase_dimension": 10,
            "amplitude_space": "full_edge",
            "amplitude_dimension": 15,
            "coherent_block_size": BLOCK_SIZE,
            "promotion_model": PROMOTION_MODEL,
            "finite_ns_qlan_fisher_factor": FINITE_NS_QLAN_FISHER_FACTOR,
            "summary_path": str(path.resolve()),
        }
        for metric in METRICS:
            value = _as_finite_float(row.get(metric), path=path, field=f"rows[{strategy}].{metric}")
            _require(-1.0 <= value <= 1.0, path, f"rows[{strategy}].{metric} lies outside [-1,1]")
            clean[metric] = value
        for metric in CHI2_METRICS:
            value = _as_finite_float(row.get(metric), path=path, field=f"rows[{strategy}].{metric}")
            _require(
                0.70 <= value <= 1.10,
                path,
                f"rows[{strategy}].{metric} must lie in [0.70,1.10]",
            )
            clean[metric] = value
        clean_rows.append(clean)

    provenance = {
        "receiver_cache_npz": str(stats.get("receiver_cache_npz", "")),
        "mixed_likelihood": str(stats.get("mixed_likelihood", "")),
    }
    return clean_rows, provenance


def load_paired_rows(run_root: Path) -> tuple[list[dict[str, Any]], list[Path], dict[str, Any]]:
    paths = [summary_path(run_root, seed) for seed in SEEDS]
    missing = [path for path in paths if not path.is_file()]
    if missing:
        listing = "\n".join(f"  - {path}" for path in missing)
        raise FileNotFoundError(
            "The paired 100-ms ensemble is incomplete; the following required seed summaries "
            f"are missing:\n{listing}\nRun run_promoted_povm_ensemble.py before this script."
        )

    all_rows: list[dict[str, Any]] = []
    common_provenance: dict[str, Any] | None = None
    for seed, path in zip(SEEDS, paths, strict=True):
        rows, provenance = _validate_summary(path, seed)
        if common_provenance is None:
            common_provenance = provenance
        else:
            _require(
                provenance == common_provenance,
                path,
                "receiver-cache or likelihood provenance differs across paired seeds",
            )
        all_rows.extend(rows)
    return all_rows, paths, common_provenance or {}


def values_by_strategy(rows: Iterable[dict[str, Any]]) -> dict[str, dict[str, np.ndarray]]:
    rows = list(rows)
    output: dict[str, dict[str, np.ndarray]] = {}
    for strategy in STRATEGIES:
        selected = sorted(
            (row for row in rows if row["strategy"] == strategy.key),
            key=lambda row: int(row["seed"]),
        )
        if [int(row["seed"]) for row in selected] != list(SEEDS):
            raise InputValidationError(f"Strategy {strategy.key} does not contain the exact paired seed set")
        output[strategy.key] = {
            metric: np.asarray([float(row[metric]) for row in selected], dtype=float)
            for metric in (*METRICS, *CHI2_METRICS)
        }
    return output


def chi2_statistics(
    values: dict[str, dict[str, np.ndarray]],
) -> dict[str, dict[str, dict[str, float]]]:
    output: dict[str, dict[str, dict[str, float]]] = {}
    for strategy in STRATEGIES:
        output[strategy.key] = {}
        for metric in CHI2_METRICS:
            sample = values[strategy.key][metric]
            sample_std = float(np.std(sample, ddof=1))
            output[strategy.key][metric] = {
                "mean": float(np.mean(sample)),
                "sem": sample_std / math.sqrt(sample.size),
                "sample_std": sample_std,
            }
    return output


def write_chi2_table(
    path: Path,
    statistics: dict[str, dict[str, dict[str, float]]],
) -> None:
    labels = {
        "edge_uniform": "Uniform edge-first",
        "optimal_singlecopy": "Optimal single-copy POVM",
        "promoted_singlecopy": rf"Joint POVM, $n_s={BLOCK_SIZE}$",
    }
    lines = [
        r"\begin{table}[t]",
        r"\caption{Componentwise reduced residuals for the three common-prior RML "
        r"reconstructions. The same regularizers and low-residual target "
        r"$\bar{\chi}^{2}=0.85$, with candidate window "
        r"$0.75\leq\bar{\chi}^{2}\leq1.00$, are used for every receiver and "
        r"noise realization. Entries are the mean $\pm$ standard error over twelve "
        r"paired noise seeds.}",
        r"\label{tab:rml_chi2}",
        r"\centering",
        r"\small",
        r"\begin{ruledtabular}",
        r"\begin{tabular}{lcc}",
        r"Receiver & $\bar{\chi}^{2}_{\rm amp}$ & $\bar{\chi}^{2}_{\Phi}$ \\",
        r"\hline",
    ]
    for strategy in STRATEGIES:
        amp = statistics[strategy.key]["amp_chi2"]
        phase = statistics[strategy.key]["phase_chi2"]
        lines.append(
            f"{labels[strategy.key]} & "
            f"${amp['mean']:.3f} \\pm {amp['sem']:.3f}$ & "
            f"${phase['mean']:.3f} \\pm {phase['sem']:.3f}$ \\\\"
        )
    lines.extend(
        [
            r"\end{tabular}",
            r"\end{ruledtabular}",
            r"\end{table}",
        ]
    )
    path.write_text("\n".join(lines) + "\n")


def bootstrap_mean_interval(
    values: np.ndarray,
    *,
    rng: np.random.Generator,
    n_resamples: int,
) -> tuple[float, float]:
    if n_resamples < 1:
        raise ValueError("bootstrap resamples must be positive")
    indices = rng.integers(0, values.size, size=(n_resamples, values.size))
    bootstrap_means = np.mean(values[indices], axis=1)
    low, high = np.quantile(bootstrap_means, (0.025, 0.975))
    return float(low), float(high)


def describe(
    values: np.ndarray,
    *,
    rng: np.random.Generator,
    n_resamples: int,
) -> dict[str, float | int]:
    if values.ndim != 1 or values.size != len(SEEDS):
        raise ValueError(f"expected one value for each of {len(SEEDS)} paired seeds")
    sample_std = float(np.std(values, ddof=1))
    ci_low, ci_high = bootstrap_mean_interval(values, rng=rng, n_resamples=n_resamples)
    return {
        "n_seed": int(values.size),
        "mean": float(np.mean(values)),
        "sample_std": sample_std,
        "sem": sample_std / math.sqrt(values.size),
        "bootstrap_ci95_lower": ci_low,
        "bootstrap_ci95_upper": ci_high,
        "min": float(np.min(values)),
        "max": float(np.max(values)),
    }


def compute_statistics(
    values: dict[str, dict[str, np.ndarray]],
    *,
    n_resamples: int,
) -> tuple[dict[str, Any], dict[str, Any], list[dict[str, Any]]]:
    rng = np.random.default_rng(BOOTSTRAP_SEED)
    strategy_stats: dict[str, Any] = {metric: {} for metric in METRICS}
    difference_stats: dict[str, Any] = {metric: {} for metric in METRICS}
    csv_rows: list[dict[str, Any]] = []

    for metric in METRICS:
        for strategy in STRATEGIES:
            stats = describe(values[strategy.key][metric], rng=rng, n_resamples=n_resamples)
            strategy_stats[metric][strategy.key] = stats
            csv_rows.append(
                {
                    "analysis_type": "strategy",
                    "metric": metric,
                    "key": strategy.key,
                    "label": strategy.short_label,
                    "minuend": "",
                    "subtrahend": "",
                    **stats,
                }
            )

        for comparison in COMPARISONS:
            paired_difference = (
                values[comparison.minuend][metric] - values[comparison.subtrahend][metric]
            )
            stats = describe(paired_difference, rng=rng, n_resamples=n_resamples)
            difference_stats[metric][comparison.key] = {
                "definition": comparison.label,
                "minuend": comparison.minuend,
                "subtrahend": comparison.subtrahend,
                "seedwise_values": [float(item) for item in paired_difference],
                **stats,
            }
            csv_rows.append(
                {
                    "analysis_type": "paired_difference",
                    "metric": metric,
                    "key": comparison.key,
                    "label": comparison.label,
                    "minuend": comparison.minuend,
                    "subtrahend": comparison.subtrahend,
                    **stats,
                }
            )
    return strategy_stats, difference_stats, csv_rows


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        raise ValueError(f"refusing to write empty CSV {path}")
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def correlation_ylim(metric_values: list[np.ndarray]) -> tuple[float, float]:
    values = np.concatenate(metric_values)
    span = max(float(np.ptp(values)), 0.025)
    pad = 0.16 * span
    lower = max(-1.0, float(np.min(values)) - pad)
    upper = min(1.0, float(np.max(values)) + pad)
    if upper - lower < 0.08:
        center = 0.5 * (upper + lower)
        lower = max(-1.0, center - 0.04)
        upper = min(1.0, center + 0.04)
    return lower, upper


def load_loop_gains(cache_path: Path) -> tuple[dict[str, np.ndarray], dict[str, Any]]:
    """Return local closure-SNR gains for every wavelength--epoch sample.

    The cached matrices are nuisance-marginalized covariances in the physical
    balanced-loop coordinates.  Hence the local Fisher information for loop l
    is the reciprocal diagonal variance, and the SNR gain of strategy b over a
    is sqrt(Cov_a,ll/Cov_b,ll).  We summarize the 360 positive local ratios by
    their geometric mean; 5--95% sample quantiles show uv/time variation.
    """
    if not cache_path.is_file():
        raise FileNotFoundError(f"missing receiver cache: {cache_path}")
    with np.load(cache_path) as payload:
        required = {
            "cov_edge_uniform",
            "cov_optimal_singlecopy",
            "cov_promoted_singlecopy",
            "cov_promoted_qlan",
        }
        missing = required.difference(payload.files)
        if missing:
            raise InputValidationError(
                f"receiver cache {cache_path} is missing {sorted(missing)}"
            )
        covariance = {key: np.asarray(payload[key], dtype=float) for key in required}

    expected_shape = (10, 36, 25, 25)
    for key, value in covariance.items():
        if value.shape != expected_shape:
            raise InputValidationError(
                f"receiver cache {key} has shape {value.shape}, expected {expected_shape}"
            )
    variances = {
        key: np.diagonal(value, axis1=-2, axis2=-1)[..., N_EDGE:]
        for key, value in covariance.items()
    }
    for key, value in variances.items():
        if value.shape != (10, 36, len(LOOP_LABELS)):
            raise InputValidationError(f"unexpected loop-variance shape for {key}: {value.shape}")
        if not np.all(np.isfinite(value)) or np.any(value <= 0.0):
            raise InputValidationError(f"nonpositive or nonfinite loop variance for {key}")

    gains = {
        "optimal_vs_edge": np.sqrt(
            variances["cov_edge_uniform"] / variances["cov_optimal_singlecopy"]
        ),
        "promoted_vs_edge": np.sqrt(
            variances["cov_edge_uniform"] / variances["cov_promoted_singlecopy"]
        ),
        "promoted_vs_parent": np.sqrt(
            variances["cov_optimal_singlecopy"]
            / variances["cov_promoted_singlecopy"]
        ),
        "qlan_vs_edge": np.sqrt(
            variances["cov_edge_uniform"] / variances["cov_promoted_qlan"]
        ),
        "qlan_vs_parent": np.sqrt(
            variances["cov_optimal_singlecopy"]
            / variances["cov_promoted_qlan"]
        ),
    }

    def summarize(array: np.ndarray) -> dict[str, Any]:
        per_loop = []
        for label, values in zip(LOOP_LABELS, np.moveaxis(array, -1, 0), strict=True):
            flat = values.reshape(-1)
            per_loop.append(
                {
                    "loop": label,
                    "n_wavelength_epoch_samples": int(flat.size),
                    "geometric_mean": float(np.exp(np.mean(np.log(flat)))),
                    "arithmetic_mean": float(np.mean(flat)),
                    "median": float(np.median(flat)),
                    "quantile_05": float(np.quantile(flat, 0.05)),
                    "quantile_95": float(np.quantile(flat, 0.95)),
                    "minimum": float(np.min(flat)),
                    "maximum": float(np.max(flat)),
                }
            )
        return {
            "definition": "local SNR gain from reciprocal nuisance-marginalized loop variance",
            "aggregation": "geometric mean over 10 wavelength bins x 36 epochs; 5--95% sample quantiles",
            "per_loop": per_loop,
            "all_samples_geometric_mean": float(np.exp(np.mean(np.log(array)))),
            "all_samples_minimum": float(np.min(array)),
            "all_samples_maximum": float(np.max(array)),
        }

    statistics = {key: summarize(value) for key, value in gains.items()}
    statistics["receiver_cache"] = str(cache_path.resolve())
    return gains, statistics


def plot_statistics(
    values: dict[str, dict[str, np.ndarray]],
    strategy_stats: dict[str, Any],
    loop_gains: dict[str, np.ndarray],
    loop_gain_stats: dict[str, Any],
    *,
    pdf_path: Path,
    png_path: Path,
) -> None:
    style = {
        "font.family": "sans-serif",
        "font.size": 7.5,
        "axes.labelsize": 8.0,
        "axes.titlesize": 8.3,
        "xtick.labelsize": 7.0,
        "ytick.labelsize": 7.0,
        "legend.fontsize": 6.8,
        "axes.linewidth": 0.65,
        "xtick.major.width": 0.55,
        "ytick.major.width": 0.55,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
    with plt.rc_context(style):
        fig, axes = plt.subplots(
            1,
            2,
            figsize=(7.25, 3.05),
            gridspec_kw={"width_ratios": [1.02, 1.48]},
        )
        ax = axes[0]
        ax_right = ax.twinx()
        x = np.arange(len(STRATEGIES), dtype=float)
        bar_width = 0.34
        rng = np.random.default_rng(31415)
        for target_ax, offset, metric, hatch, alpha in (
            (ax, -bar_width / 2.0, "blr_corr", "", 0.96),
            (ax_right, bar_width / 2.0, "global_corr", "//", 0.46),
        ):
            means = [float(strategy_stats[metric][item.key]["mean"]) for item in STRATEGIES]
            sems = [float(strategy_stats[metric][item.key]["sem"]) for item in STRATEGIES]
            target_ax.bar(
                x + offset,
                means,
                width=bar_width,
                yerr=sems,
                capsize=2.0,
                color=[item.color for item in STRATEGIES],
                alpha=alpha,
                edgecolor="0.18",
                linewidth=0.55,
                hatch=hatch,
                zorder=2,
            )
            for index, strategy in enumerate(STRATEGIES):
                seed_values = values[strategy.key][metric]
                jitter = rng.normal(0.0, 0.013, seed_values.size)
                target_ax.scatter(
                    np.full(seed_values.size, x[index] + offset) + jitter,
                    seed_values,
                    s=9.5,
                    color=strategy.color,
                    edgecolor="white",
                    linewidth=0.25,
                    alpha=0.84,
                    zorder=3,
                )
        ax.set_xticks(x, [item.plot_label for item in STRATEGIES])
        ax.set_xlim(-0.48, len(STRATEGIES) - 0.52)
        ax.set_ylim(
            *correlation_ylim([values[item.key]["blr_corr"] for item in STRATEGIES])
        )
        ax_right.set_ylim(
            *correlation_ylim([values[item.key]["global_corr"] for item in STRATEGIES])
        )
        ax.set_ylabel("BLR correlation")
        ax_right.set_ylabel("all-pixel correlation")
        ax.set_title("Image fidelity (12 paired seeds)", pad=4.0)
        ax.grid(axis="y", color="0.88", lw=0.5)
        ax.set_axisbelow(True)
        ax.legend(
            handles=[
                Patch(facecolor="0.45", edgecolor="0.18", label=r"BLR mean $\pm$ SEM"),
                Patch(
                    facecolor="0.72",
                    edgecolor="0.18",
                    hatch="//",
                    alpha=0.55,
                    label=r"all-pixel mean $\pm$ SEM",
                ),
            ],
            loc="upper left",
            frameon=False,
            handlelength=1.25,
            borderaxespad=0.15,
        )
        ax.text(
            -0.19,
            1.04,
            "(a)",
            transform=ax.transAxes,
            ha="left",
            va="bottom",
            fontsize=8.4,
            fontweight="bold",
        )

        ax = axes[1]
        x_loop = np.arange(len(LOOP_LABELS), dtype=float)
        gain_width = 0.25
        gain_specs = (
            ("optimal_vs_edge", -gain_width, "Optimal single-copy", STRATEGIES[1].color),
            ("promoted_vs_edge", 0.0, rf"Joint POVM $n_s={BLOCK_SIZE}$", STRATEGIES[2].color),
            ("qlan_vs_edge", gain_width, "Asymptotic limit", QLAN_COLOR),
        )
        for key, offset, label, color in gain_specs:
            records = loop_gain_stats[key]["per_loop"]
            centers = np.asarray([float(item["geometric_mean"]) for item in records])
            lower = centers - np.asarray([float(item["quantile_05"]) for item in records])
            upper = np.asarray([float(item["quantile_95"]) for item in records]) - centers
            ax.bar(
                x_loop + offset,
                centers,
                width=gain_width,
                yerr=np.vstack([lower, upper]),
                capsize=1.8,
                color=color,
                edgecolor="0.18",
                linewidth=0.5,
                label=label,
                zorder=2,
            )
        ax.axhline(1.0, color="0.25", lw=0.8, ls="--")
        ax.set_xticks(x_loop, LOOP_LABELS, rotation=42, ha="right")
        ax.set_ylabel("closure SNR gain vs edge-first")
        upper_gain = max(
            float(item["quantile_95"])
            for key in ("optimal_vs_edge", "promoted_vs_edge", "qlan_vs_edge")
            for item in loop_gain_stats[key]["per_loop"]
        )
        ax.set_ylim(0.8, 1.10 * upper_gain)
        ax.set_title("Per-loop receiver gain", pad=4.0)
        ax.grid(axis="y", color="0.88", lw=0.5)
        ax.set_axisbelow(True)
        ax.legend(frameon=False, loc="upper right", fontsize=6.6)
        parent_records = loop_gain_stats["promoted_vs_parent"]["per_loop"]
        parent_min = min(float(item["geometric_mean"]) for item in parent_records)
        parent_max = max(float(item["geometric_mean"]) for item in parent_records)
        ax.text(
            0.02,
            0.97,
            rf"$n_s={BLOCK_SIZE}$ / parent: ${parent_min:.2f}$--${parent_max:.2f}\times$",
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=6.8,
        )
        ax.text(
            -0.105,
            1.04,
            "(b)",
            transform=ax.transAxes,
            ha="left",
            va="bottom",
            fontsize=8.4,
            fontweight="bold",
        )
        fig.text(
            0.5,
            0.018,
            rf"100 ms; phase: closure subspace $C=10$; amplitude: full edge space $E=15$; "
            rf"finite $n_s={BLOCK_SIZE}$ POVM and asymptotic limit; loop bars: geometric mean, whiskers: 5--95% over $(\lambda,t)$",
            ha="center",
            va="bottom",
            fontsize=6.6,
        )
        fig.subplots_adjust(left=0.083, right=0.925, bottom=0.265, top=0.90, wspace=0.43)
        fig.savefig(pdf_path, bbox_inches="tight")
        fig.savefig(png_path, dpi=400, bbox_inches="tight")
        plt.close(fig)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-root", type=Path, default=DEFAULT_RUN_ROOT)
    parser.add_argument("--result-dir", type=Path, default=DEFAULT_RESULT_DIR)
    parser.add_argument("--figure-dir", type=Path, default=DEFAULT_FIGURE_DIR)
    parser.add_argument(
        "--skip-figure",
        action="store_true",
        help="Write the numerical statistics without rendering the superseded wide-layout figure.",
    )
    parser.add_argument("--receiver-cache", type=Path, default=DEFAULT_RECEIVER_CACHE)
    parser.add_argument("--stem", default=DEFAULT_STEM)
    parser.add_argument(
        "--bootstrap-resamples",
        type=int,
        default=DEFAULT_BOOTSTRAP_RESAMPLES,
        help="Number of fixed-seed percentile-bootstrap resamples.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.bootstrap_resamples < 1:
        raise ValueError("--bootstrap-resamples must be positive")

    rows, input_paths, provenance = load_paired_rows(args.run_root)
    values = values_by_strategy(rows)
    strategy_stats, difference_stats, summary_csv_rows = compute_statistics(
        values,
        n_resamples=args.bootstrap_resamples,
    )
    component_chi2 = chi2_statistics(values)
    chi2_receiver_spreads = {}
    for metric in CHI2_METRICS:
        means = np.asarray(
            [component_chi2[strategy.key][metric]["mean"] for strategy in STRATEGIES],
            dtype=float,
        )
        ratio = float(np.max(means) / np.min(means))
        chi2_receiver_spreads[metric] = {
            "minimum_mean": float(np.min(means)),
            "maximum_mean": float(np.max(means)),
            "max_to_min_ratio": ratio,
        }
        if ratio > 1.10 + 1.0e-12:
            raise ValueError(
                f"The three receiver means for {metric} are not matched within 10%: "
                f"max/min={ratio:.4f}. Rerun or inspect the common RML selection."
            )
    loop_gains, loop_gain_stats = load_loop_gains(args.receiver_cache)

    args.result_dir.mkdir(parents=True, exist_ok=True)
    args.figure_dir.mkdir(parents=True, exist_ok=True)
    raw_csv = args.result_dir / f"{args.stem}_seed_metrics.csv"
    stats_csv = args.result_dir / f"{args.stem}_statistics.csv"
    stats_json = args.result_dir / f"{args.stem}_statistics.json"
    chi2_tex = args.result_dir / f"{args.stem}_chi2_table.tex"
    pdf_path = args.figure_dir / f"{args.stem}.pdf"
    png_path = args.figure_dir / f"{args.stem}.png"

    write_csv(raw_csv, rows)
    write_csv(stats_csv, summary_csv_rows)
    write_chi2_table(chi2_tex, component_chi2)
    if not args.skip_figure:
        plot_statistics(
            values,
            strategy_stats,
            loop_gains,
            loop_gain_stats,
            pdf_path=pdf_path,
            png_path=png_path,
        )

    payload = {
        "schema_version": 2,
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "analysis": "paired main-text Fig. 4 receiver statistics",
        "metadata": {
            "dataset": "single paired 100-ms ensemble; no legacy or modular inputs",
            "n_station": 6,
            "n_seed": len(SEEDS),
            "seeds": list(SEEDS),
            "strategies": [strategy.key for strategy in STRATEGIES],
            "phase_parameter_space": "closure subspace only",
            "phase_dimension_C": 10,
            "amplitude_parameter_space": "complete edge space",
            "amplitude_dimension_E": 15,
            "coherent_block_size_ns": BLOCK_SIZE,
            "promotion_model": PROMOTION_MODEL,
            "finite_block_interpretation": (
                "finite-copy covariance supplied by the configured receiver cache; "
                "QLAN retained only as an asymptotic loop-gain reference"
            ),
            "paired_noise_draws": True,
            "effective_exposure_s": 0.100,
            "existing_coupled_area_fraction": 1.0,
            "remote_diameter_m": 6.0,
            "photon_collection_efficiency": 0.02,
            "amplitude_branch_fraction": 0.5,
            "phase_branch_fraction": 0.5,
            "reconstruction_selection": (
                "one fixed Gaussian/TV/entropy regularization, with no translation-gauge "
                "or morphology-specific core prior, plus one receiver-blind, data-only "
                "componentwise target chi-square of 0.85 with a 0.75--1.00 "
                "candidate window for every seed and receiver"
            ),
            "bootstrap": {
                "method": "paired nonparametric percentile bootstrap of the mean",
                "confidence_level": 0.95,
                "rng_seed": BOOTSTRAP_SEED,
                "n_resamples": args.bootstrap_resamples,
            },
            **provenance,
        },
        "input_summary_files": [str(path.resolve()) for path in input_paths],
        "strategy_statistics": strategy_stats,
        "paired_difference_statistics": difference_stats,
        "component_chi2_statistics": component_chi2,
        "component_chi2_receiver_spreads": chi2_receiver_spreads,
        "per_loop_snr_gain_statistics": loop_gain_stats,
        "outputs": {
            "seed_metrics_csv": str(raw_csv.resolve()),
            "statistics_csv": str(stats_csv.resolve()),
            "statistics_json": str(stats_json.resolve()),
            "chi2_table_tex": str(chi2_tex.resolve()),
            "figure_pdf": None if args.skip_figure else str(pdf_path.resolve()),
            "figure_png": None if args.skip_figure else str(png_path.resolve()),
        },
    }
    stats_json.write_text(json.dumps(payload, indent=2) + "\n")

    if not args.skip_figure:
        print(pdf_path)
        print(png_path)
    print(raw_csv)
    print(stats_csv)
    print(stats_json)
    print(chi2_tex)


if __name__ == "__main__":
    main()
