from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from audit_20260608_common import OUT


def sci(value: float) -> str:
    return f"{float(value):.3e}"


def detailed_eq19_derivation_lines() -> list[str]:
    return [
        r"\section{From the noisy one-click model to Eq. (19)}",
        r"\subsection{One-click probabilities, Fisher information, and the SLD}",
        r"Start with the station modes arriving at the common hub.  For one temporal-frequency mode in the",
        r"weak-source limit, all source and background information relevant to one-click photon counting is",
        r"encoded in an unnormalized positive matrix $\rho_{\cal B}$.  For a passive sorter followed by",
        r"photon counting in output projectors $\Pi_y$, the mean one-click probability/intensity in channel",
        r"$y$ is",
        r"\begin{equation}",
        r"p_y(\theta)={\rm Tr}(\Pi_y\rho_{\cal B}(\theta)),\qquad",
        r"\partial_\theta p_y={\rm Tr}(\Pi_yD_\theta),\quad D_\theta\equiv\partial_\theta\rho_{\cal B}.",
        r"\label{eq:audit_click_prob}",
        r"\end{equation}",
        r"The corresponding classical Fisher information for that fixed sorter is",
        r"\begin{equation}",
        r"F_{\rm C}(\theta)=\sum_y\frac{[{\rm Tr}(\Pi_yD_\theta)]^2}{{\rm Tr}(\Pi_y\rho_{\cal B})}.",
        r"\label{eq:audit_cfi_basic}",
        r"\end{equation}",
        r"The optimal direct receiver for a scalar parameter is obtained from the symmetric logarithmic",
        r"derivative (SLD) $L_\theta$, defined by",
        r"\begin{equation}",
        r"D_\theta=\frac{1}{2}(\rho_{\cal B}L_\theta+L_\theta\rho_{\cal B}).",
        r"\label{eq:audit_sld_basic}",
        r"\end{equation}",
        r"Diagonalizing $L_\theta$ and photon-counting in its eigenmodes attains the one-click quantum Fisher",
        r"information",
        r"\begin{equation}",
        r"F_{\rm Q}(\theta)={\rm Re}\,{\rm Tr}(D_\theta L_\theta)={\rm Tr}(\rho_{\cal B}L_\theta^2),",
        r"\label{eq:audit_qfi_basic}",
        r"\end{equation}",
        r"where the second equality follows by substituting Eq. (\ref{eq:audit_sld_basic}) and cyclically",
        r"moving factors under the trace.  The same result is obtained in the eigenbasis",
        r"$\rho_{\cal B}=\sum_m\lambda_m|m\rangle\langle m|$ as",
        r"\begin{equation}",
        r"F_{\rm Q}(\theta)=\sum_{mn:\lambda_m+\lambda_n>0}",
        r"\frac{2|D_{\theta,mn}|^2}{\lambda_m+\lambda_n}.",
        r"\label{eq:audit_qfi_eigen}",
        r"\end{equation}",
        r"Because $\rho_{\cal B}$ is unnormalized, these Fisher informations are per temporal-frequency mode;",
        r"the broadband simulations multiply them by the number of modes, i.e. exposure time times bandwidth.",
        r"\subsection{General direct-receiver statistical model}",
        r"For one temporal-frequency mode, after propagation to the common optical hub, the weak-source",
        r"counting model is represented by an unnormalized one-click matrix $\rho_{\cal B}$.  In an",
        r"$N$-station direct sorter this matrix is",
        r"\begin{equation}",
        r"(\rho_{\cal B})_{ii}=s_i^{\rm dir},\qquad",
        r"(\rho_{\cal B})_{ij}=g_{ij}e^{i\phi_{ij}}\quad (i\ne j).",
        r"\label{eq:audit_general_rhob}",
        r"\end{equation}",
        r"The diagonal load is",
        r"\begin{equation}",
        r"s_i^{\rm dir}=\eta_i u_i+\epsilon_i+\epsilon_{{\rm dir},i}.",
        r"\label{eq:audit_direct_load}",
        r"\end{equation}",
        r"Here $u_i$ is the source occupation in the collected station mode, $\eta_i$ is the transport and",
        r"capture efficiency, $\epsilon_i$ is the station-local false-positive/background occupancy, and",
        r"$\epsilon_{{\rm dir},i}$ is excess background in the direct sorter.  The coherent off-diagonal",
        r"amplitude is",
        r"\begin{equation}",
        r"g_{ij}=\sqrt{\eta_i\eta_j u_i u_j}\,|\nu_{ij}|,",
        r"\label{eq:audit_coherent_amplitude}",
        r"\end{equation}",
        r"with the visibility phase absorbed into $\phi_{ij}$.  This is the noise model that enters the",
        r"direct SLD calculation.  By contrast, a pairwise edge-first combiner has a separate baseline",
        r"denominator",
        r"\begin{equation}",
        r"p_{ij}^{\rm sep}=f(s_i+s_j)+\epsilon_{\rm pair},\qquad s_i=\eta_i u_i+\epsilon_i,",
        r"\label{eq:audit_pair_load}",
        r"\end{equation}",
        r"so $\epsilon_{\rm pair}$ affects the edge-first Fisher in Eq. (13) of the paper, but it is not part",
        r"of the direct-sorter $\rho_{\cal B}$ in Eq. (\ref{eq:audit_general_rhob}).",
        r"",
        r"For the local three-station derivation we choose the phase frame in which the three coherent",
        r"amplitudes are real and positive.  With oriented edges $(12),(23),(31)$,",
        r"\begin{equation}",
        r"\rho_{\cal B}=",
        r"\begin{pmatrix}",
        r"s_1 & g_{12} & g_{31}\\",
        r"g_{12} & s_2 & g_{23}\\",
        r"g_{31} & g_{23} & s_3",
        r"\end{pmatrix},",
        r"\label{eq:audit_three_rhob}",
        r"\end{equation}",
        r"where in the direct benchmark $s_i=s_i^{\rm dir}$.  This is the only place where the independent",
        r"station background and direct-sorter excess enter Eq. (19): they increase the diagonal entries of",
        r"$\rho_{\cal B}$ and therefore change the SLD metric.",
        r"\subsection{Edge phase tangents}",
        r"The oriented edge currents are",
        r"\begin{align}",
        r"A_{12}&=i(|1\rangle\langle2|-|2\rangle\langle1|),\\",
        r"A_{23}&=i(|2\rangle\langle3|-|3\rangle\langle2|),\\",
        r"A_{31}&=i(|3\rangle\langle1|-|1\rangle\langle3|).",
        r"\end{align}",
        r"Differentiating Eq. (\ref{eq:audit_three_rhob}) with respect to the edge phases at the real",
        r"working point gives",
        r"\begin{equation}",
        r"D_e\equiv \partial_{\phi_e}\rho_{\cal B}=g_eA_e,\qquad",
        r"e\in\{12,23,31\}.",
        r"\label{eq:audit_edge_tangents}",
        r"\end{equation}",
        r"Each $D_e$ is Hermitian and imaginary antisymmetric.  The edge-phase QFI matrix $J$ is obtained from",
        r"the individual SLDs $L_e$ satisfying",
        r"\begin{equation}",
        r"\frac{1}{2}(\rho_{\cal B}L_e+L_e\rho_{\cal B})=D_e,\qquad",
        r"J_{ee'}={\rm Re}\,{\rm Tr}(D_eL_{e'}).",
        r"\label{eq:audit_edge_qfi}",
        r"\end{equation}",
        r"The same formula is used by the code through the eigenbasis expression",
        r"$J_{ee'}=\sum_{mn}2\,{\rm Re}[(D_e)_{mn}(D_{e'})_{nm}]/(\lambda_m+\lambda_n)$.",
        r"\subsection{Eliminating station-piston nuisance directions}",
        r"The physical closure phase is protected against station-piston shifts.  In edge coordinates, write",
        r"a scalar closure displacement and two station-gauge displacements as",
        r"\begin{equation}",
        r"\delta\boldsymbol{\phi}=v\,\delta\Phi_{\rm cl}+C\,\delta\boldsymbol{\psi},\qquad",
        r"v=\frac{1}{3}\begin{pmatrix}1\\1\\1\end{pmatrix},\qquad",
        r"C=\begin{pmatrix}-1&0\\1&-1\\0&1\end{pmatrix}.",
        r"\label{eq:audit_closure_gauge_decomp}",
        r"\end{equation}",
        r"The Fisher matrix for $(\Phi_{\rm cl},\boldsymbol{\psi})$ is therefore the block matrix built from",
        r"$v^{\mathsf T}Jv$, $v^{\mathsf T}JC$, and $C^{\mathsf T}JC$.  Marginalizing the two nuisance piston",
        r"coordinates gives the Schur complement",
        r"\begin{equation}",
        r"F_{\rm cl}^{\rm opt}=v^{\mathsf T}Jv-v^{\mathsf T}JC(C^{\mathsf T}JC)^+C^{\mathsf T}Jv.",
        r"\label{eq:audit_schur}",
        r"\end{equation}",
        r"Equivalently define",
        r"\begin{equation}",
        r"\beta=(C^{\mathsf T}JC)^+C^{\mathsf T}Jv,\qquad",
        r"q_{\rm eff}=v-C\beta.",
        r"\label{eq:audit_qeff}",
        r"\end{equation}",
        r"Then",
        r"\begin{equation}",
        r"F_{\rm cl}^{\rm opt}=q_{\rm eff}^{\mathsf T}Jq_{\rm eff},\qquad",
        r"D_{\rm eff}=\sum_e(q_{\rm eff})_eD_e.",
        r"\label{eq:audit_deff}",
        r"\end{equation}",
        r"This step is important: the tangent that enters Eq. (19) is the SLD-efficient closure tangent after",
        r"piston nuisance removal, not necessarily the naive equal vector $v$ when the triangle is",
        r"asymmetric.",
        r"\subsection{Why the SLD lies in the current space}",
        r"At the real working point, $\rho_{\cal B}$ in Eq. (\ref{eq:audit_three_rhob}) is real symmetric,",
        r"whereas $D_{\rm eff}$ is imaginary antisymmetric.  The SLD superoperator",
        r"\begin{equation}",
        r"{\cal L}_{\rho}(X)=\frac{1}{2}(\rho_{\cal B}X+X\rho_{\cal B})",
        r"\label{eq:audit_sld_superoperator}",
        r"\end{equation}",
        r"maps imaginary antisymmetric Hermitian matrices to imaginary antisymmetric Hermitian matrices.",
        r"Thus the SLD solution for this tangent lives in the three-dimensional current subspace spanned by",
        r"$A_{12},A_{23},A_{31}$ (up to the usual Moore-Penrose convention on null eigenspaces).  We may",
        r"therefore write",
        r"\begin{equation}",
        r"L_{\rm cl}=x_{12}A_{12}+x_{23}A_{23}+x_{31}A_{31}.",
        r"\label{eq:audit_l_current}",
        r"\end{equation}",
        r"Substituting Eq. (\ref{eq:audit_l_current}) into",
        r"${\cal L}_{\rho}(L_{\rm cl})=D_{\rm eff}$ and testing the result against each current generator",
        r"gives",
        r"\begin{equation}",
        r"\sum_{e'}{\cal M}_{ee'}x_{e'}=b_e,",
        r"\label{eq:audit_eq19_main}",
        r"\end{equation}",
        r"with",
        r"\begin{equation}",
        r"{\cal M}_{ee'}=\frac{1}{2}{\rm Re}\,{\rm Tr}\!\left[A_e(\rho_{\cal B}A_{e'}+A_{e'}\rho_{\cal B})\right],",
        r"\qquad",
        r"b_e={\rm Re}\,{\rm Tr}(A_eD_{\rm eff}).",
        r"\label{eq:audit_eq19_coeffs}",
        r"\end{equation}",
        r"This is Eq. (19) of the manuscript.  Its Fisher information is",
        r"\begin{equation}",
        r"F_{\rm cl}^{\rm opt}={\rm Re}\,{\rm Tr}(D_{\rm eff}L_{\rm cl})=x^{\mathsf T}b=x^{\mathsf T}{\cal M}x.",
        r"\label{eq:audit_fisher_from_x}",
        r"\end{equation}",
        r"\subsection{Explicit noisy-triangle form}",
        r"For the matrix in Eq. (\ref{eq:audit_three_rhob}) and the edge order $(12),(23),(31)$,",
        r"Eq. (\ref{eq:audit_eq19_main}) becomes",
        r"\begin{equation}",
        r"\begin{pmatrix}",
        r"s_1+s_2 & -g_{31} & -g_{23}\\",
        r"-g_{31} & s_2+s_3 & -g_{12}\\",
        r"-g_{23} & -g_{12} & s_3+s_1",
        r"\end{pmatrix}",
        r"\begin{pmatrix}x_{12}\\x_{23}\\x_{31}\end{pmatrix}",
        r"=2\begin{pmatrix}",
        r"(q_{\rm eff})_{12}g_{12}\\",
        r"(q_{\rm eff})_{23}g_{23}\\",
        r"(q_{\rm eff})_{31}g_{31}",
        r"\end{pmatrix}.",
        r"\label{eq:audit_explicit_m}",
        r"\end{equation}",
        r"This last expression makes the noise dependence transparent.  Increasing station-local background",
        r"or direct-sorter excess increases the corresponding $s_i$ on the diagonal of the SLD metric.  Fibre",
        r"loss and visibility loss reduce the $g_{ij}$ entries and the right-hand side.  Pair-combiner noise",
        r"$\epsilon_{\rm pair}$ does not enter this direct SLD equation; it only enters the edge-first",
        r"denominator used for the comparison gain.",
        r"\subsection{Algebraic check of the right-hand side and metric}",
        r"The explicit form in Eq. (\ref{eq:audit_explicit_m}) follows from two elementary traces.  First,",
        r"with the present orientation,",
        r"\begin{equation}",
        r"{\rm Re}\,{\rm Tr}(A_eA_{e'})=2\delta_{ee'},",
        r"\end{equation}",
        r"so",
        r"\begin{equation}",
        r"b_e={\rm Re}\,{\rm Tr}\left[A_e\sum_{e'}(q_{\rm eff})_{e'}g_{e'}A_{e'}\right]",
        r"=2(q_{\rm eff})_eg_e.",
        r"\end{equation}",
        r"Second, direct multiplication of",
        r"$A_e\rho_{\cal B}A_{e'}+A_eA_{e'}\rho_{\cal B}$ gives the diagonal entries",
        r"${\cal M}_{12,12}=s_1+s_2$, ${\cal M}_{23,23}=s_2+s_3$, and",
        r"${\cal M}_{31,31}=s_3+s_1$, while the off-diagonal entries are the negative coherent",
        r"amplitudes on the edge opposite the two currents, e.g.",
        r"${\cal M}_{12,23}=-g_{31}$.  This gives the matrix in Eq. (\ref{eq:audit_explicit_m}) and",
        r"therefore Eq. (19) without dropping any noise terms.",
    ]


def gain_factor_lines(gain: dict[str, object] | None) -> list[str]:
    if not gain:
        return []
    lines = [
        r"\section{Why Fig. 1(a) and Fig. 3(b) show different single-loop gains}",
        r"The apparent discrepancy is a comparison-of-denominators issue plus a source-regime issue.  Fig. 1(a)",
        r"plots a local three-station quantity",
        r"\begin{equation}",
        r"G_{\rm Fig1}=\left(\frac{F_{\rm direct}^{\rm raw}}{F_{\rm edge}^{f=1/2}}\right)^{1/2},",
        r"\label{eq:audit_gfig1}",
        r"\end{equation}",
        r"where the edge-first reference is a single isolated triangle: each station sends half its light to",
        r"each of the two incident baselines.  Fig. 3(b), in contrast, uses the complete seven-station array",
        r"with simultaneous all-baseline edge-first readout and the capacity-normalized direct proxy:",
        r"\begin{equation}",
        r"G_{\rm Fig3}=\left(\frac{F_{\rm direct}^{\rm cap}}{F_{\rm edge}^{f=1/6}}\right)^{1/2}",
        r"=\left(\frac{(2/5)F_{\rm direct}^{\rm raw}}{F_{\rm edge}^{f=1/6}}\right)^{1/2}.",
        r"\label{eq:audit_gfig3}",
        r"\end{equation}",
        r"Therefore",
        r"\begin{equation}",
        r"G_{\rm Fig3}=G_{\rm local}^{\rm actual}",
        r"\left[\frac{2}{5}\frac{F_{\rm edge}^{f=1/2}}{F_{\rm edge}^{f=1/6}}\right]^{1/2},\qquad",
        r"G_{\rm local}^{\rm actual}\equiv",
        r"\left(\frac{F_{\rm direct}^{\rm raw}}{F_{\rm edge}^{f=1/2}}\right)^{1/2}.",
        r"\label{eq:audit_gain_decomp}",
        r"\end{equation}",
        r"The bracketed factor is the resource-normalization factor.  The direct side is scaled by the",
        r"capacity proxy $2/5$; the edge-first side is also much weaker because in the complete array",
        r"each station sends only $1/6$ of its light to a given baseline rather than $1/2$.  In the present",
        r"weak-source/background-loaded regime, that edge penalty is large enough that the net resource factor",
        r"still exceeds unity.",
        r"\begin{center}",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"loop & $G_{\rm local}^{\rm actual}$ & $G_{\rm Fig3}$ & resource factor & $\sqrt{F_{1/2}/F_{1/6}}$ \\",
        r"\midrule",
    ]
    for row in gain["rows"]:
        lines.append(
            f"{row['loop']} & {row['fig1_like_raw_direct_over_triangle_half_edge_snr']:.3f} & "
            f"{row['fig3_scheduled_direct_over_uniform_edge_snr']:.3f} & "
            f"{row['resource_factor_fig3_over_fig1_like']:.3f} & "
            f"{row['sqrt_edge_half_over_uniform']:.3f} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{center}",
            r"The local gains in this table are already larger than the 1.42--1.58 range of Fig. 1(a),",
            r"because Fig. 1(a) intentionally fixes a reference heat-map model with $\nu_{\max}=0.3$ and equal",
            r"station loads.  The NGC 4151 simulation has chromatic, source-dependent visibilities; some of the",
            r"representative loops, especially the compact loop 123, sample higher-coherence structure than that",
            r"reference heat-map point.  Thus the Fig. 3(b) bars are not expected to equal the Fig. 1(a) color",
            r"scale: they combine the actual source-dependent local gain with the full-array resource factor.",
        ]
    )
    return lines


def write_derivation_tex(
    eq19: dict[str, object],
    fig1: dict[str, object],
    fig3: dict[str, object],
    gain: dict[str, object] | None = None,
) -> Path:
    tex = OUT / "eq19_fig1_fig3_self_consistency_note.tex"
    lines = [
        r"\documentclass[10pt]{article}",
        r"\usepackage[margin=0.75in]{geometry}",
        r"\usepackage{amsmath,amssymb,booktabs}",
        r"\usepackage[colorlinks=true,allcolors=blue]{hyperref}",
        r"\begin{document}",
        r"\title{Self-consistency audit for closure-space readout figures}",
        r"\author{Generated audit note}",
        r"\date{2026-06-08}",
        r"\maketitle",
        *detailed_eq19_derivation_lines(),
        r"\section{Numerical checks}",
        r"\begin{center}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"Check & Value \\",
        r"\midrule",
        f"Eq. (19) cases & {eq19['n_cases']} \\\\",
        f"max $|F_{{\\rm proj}}-F_{{\\rm Schur}}|/F_{{\\rm Schur}}$ & {sci(eq19['max_rel_projected_minus_schur'])} \\\\",
        f"max $|F_{{\\rm full}}-F_{{\\rm Schur}}|/F_{{\\rm Schur}}$ & {sci(eq19['max_rel_full_minus_schur'])} \\\\",
        f"max SLD equation residual & {sci(eq19['max_rel_sld_equation_residual'])} \\\\",
        f"max full-SLD outside-current-span residual & {sci(eq19['max_rel_full_sld_outside_current_span'])} \\\\",
        f"Fig. 1(a) max Eq. (13) grid error & {sci(fig1['max_rel_error_eq13'])} \\\\",
        f"Fig. 1(a) symmetric Eq. (16) error & {sci(fig1['symmetric_rel_error_eq16'])} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{center}",
        *gain_factor_lines(gain),
        r"\section{Fig. 2/Fig. 3 normalization audit}",
        r"The previous loop diagnostic used the raw direct QFI as its denominator.",
        r"The paper image column, however, uses the capacity-normalized direct proxy, namely the raw direct",
        r"closure-space Fisher multiplied by $6/15=2/5$ for the $N=7$, $C=15$ root-loop benchmark.",
        r"RMS values must therefore be divided by the capacity proxy in Fig. 3(b).",
        r"\begin{center}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"Quantity & Value \\",
        r"\midrule",
        f"near/proxy RMS range & {fig3['near_over_scheduled_rms_mean_range'][0]:.3f}--{fig3['near_over_scheduled_rms_mean_range'][1]:.3f} \\\\",
        f"edge/proxy RMS range & {fig3['edge_over_scheduled_rms_mean_range'][0]:.3f}--{fig3['edge_over_scheduled_rms_mean_range'][1]:.3f} \\\\",
        f"raw QFI/proxy RMS & {fig3['raw_direct_over_scheduled_rms_mean']:.3f} \\\\",
        f"proxy/raw QFI RMS & {fig3['scheduled_proxy_over_raw_direct_expected']:.3f} \\\\",
        f"near minus proxy BLR mean & {fig3['near_minus_scheduled_blr_mean']:.3f} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{center}",
        r"\end{document}",
    ]
    tex.write_text("\n".join(lines) + "\n")
    return tex


def compile_derivation_pdf(tex: Path) -> dict[str, object]:
    pdflatex = shutil.which("pdflatex")
    if pdflatex is None:
        return {"tex": str(tex), "pdf": None, "compiled": False, "reason": "pdflatex not found"}
    cmd = [pdflatex, "-interaction=nonstopmode", "-halt-on-error", tex.name]
    first = subprocess.run(cmd, cwd=tex.parent, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if first.returncode != 0:
        log = tex.with_suffix(".pdflatex.stdout")
        log.write_text(first.stdout)
        return {"tex": str(tex), "pdf": None, "compiled": False, "reason": str(log)}
    second = subprocess.run(cmd, cwd=tex.parent, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if second.returncode != 0:
        log = tex.with_suffix(".pdflatex.stdout")
        log.write_text(second.stdout)
        return {"tex": str(tex), "pdf": None, "compiled": False, "reason": str(log)}
    return {"tex": str(tex), "pdf": str(tex.with_suffix(".pdf")), "compiled": True, "reason": ""}
