from __future__ import annotations

import csv
import json
import math
import os
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib import colors
import numpy as np

import latest_maunakea_closure_snr_clean_rml as latest
import plot_augmented_existing_telescope_closure_networks as aug
import plot_augmented_existing_telescope_ngc_sources as ngc
import plot_augmented_far_snr100_weighting_test as wt
import plot_prl_broadband_blr_optimized as opt
import plot_prl_broadband_clean as base


ROOT = Path(__import__("os").environ["VLBI_HOMODYNE_ROOT"])
OUTFIG = ROOT / "output" / "figures"
OUTFIG.mkdir(parents=True, exist_ok=True)

MAUNAKEA_PLUS5_LAYOUT = OUTFIG / "maunakea_top4_plus5_ngc4151_layout.json"
OPTIMAL8_LAYOUT = OUTFIG / "optimized_array_topology_u50v50_lowuv15_near10_5_ydown1p5_hub_m3_m4.json"

SOURCE = ngc.NGC4151

N_RML = int(os.environ.get("AMP_RML_N_PIX", "96"))
N_ITER = int(os.environ.get("AMP_RML_N_ITER", "180"))
STEP = float(os.environ.get("AMP_RML_STEP", "0.018"))
OBSERVING_DAYS = int(os.environ.get("OBSERVING_DAYS", "1"))
N_TIME_WINDOWS = int(os.environ.get("N_TIME_WINDOWS", "36"))
EXPOSURE_S = float(os.environ.get("EXPOSURE_S", "600.0"))
EXPOSURE_GAP_S = float(os.environ.get("EXPOSURE_GAP_S", "150.0"))
SNR_BOOST = float(os.environ.get("AUGMENTED_SNR_BOOST", "1.0"))
FIBER_LOSS_DB_PER_KM = float(os.environ.get("FIBER_LOSS_DB_PER_KM", "0.2"))
MODE_FALSE_POSITIVE = float(os.environ.get("MODE_FALSE_POSITIVE", os.environ.get("STATION_FALSE_POSITIVE", "0.05")))
PAIR_FALSE_POSITIVE = float(os.environ.get("PAIR_FALSE_POSITIVE", "0.0"))

# These are not source-noise parameters.  They encode the assumed accuracy of
# the calibrated visibility amplitudes used as EHT-style RML constraints.
AMP_SIGMA_MODE = os.environ.get("AMP_RML_AMP_SIGMA_MODE", "physical").strip().lower()
AMP_SIGMA_ABS = float(os.environ.get("AMP_RML_AMP_SIGMA_ABS", "0.01"))
AMP_REL_SIGMA = float(os.environ.get("AMP_RML_AMP_REL_SIGMA", "0.05"))
AMP_ABS_FLOOR = float(os.environ.get("AMP_RML_AMP_ABS_FLOOR", "0.015"))
PHASE_FLOOR_RAD = float(os.environ.get("AMP_RML_PHASE_FLOOR_RAD", "0.0"))

AMP_GRAD_WEIGHT = float(os.environ.get("AMP_RML_AMP_WEIGHT", "1.20"))
PHASE_GRAD_WEIGHT = float(os.environ.get("AMP_RML_PHASE_WEIGHT", "1.00"))
PRIOR_WEIGHT = float(os.environ.get("AMP_RML_PRIOR_WEIGHT", "0.10"))
TV_WEIGHT = float(os.environ.get("AMP_RML_TV_WEIGHT", "0.045"))
ENTROPY_WEIGHT = float(os.environ.get("AMP_RML_ENTROPY_WEIGHT", "0.010"))
LINESEARCH = os.environ.get("AMP_RML_LINESEARCH", "1") == "1"


def rms(x: np.ndarray) -> float:
    value = float(np.sqrt(np.mean(np.asarray(x, dtype=float) ** 2)))
    return value if np.isfinite(value) and value > 1e-30 else 1.0


def normalize_grad(grad: np.ndarray) -> np.ndarray:
    scale = rms(grad)
    if scale <= 1e-30:
        return np.zeros_like(grad)
    return grad / scale


def amplitude_sigma(amp_data: np.ndarray, amp_sigma: np.ndarray | None = None) -> np.ndarray:
    """Return the amplitude uncertainty used by the RML likelihood.

    The default ``physical`` mode uses the per-sample visibility-amplitude
    uncertainty generated by the detector-noise model in ``simulate_bands``.
    Constant and relative modes are retained behind environment switches for
    controlled comparisons only.
    """
    amp_data = np.asarray(amp_data, dtype=float)
    if AMP_SIGMA_MODE == "physical":
        if amp_sigma is None:
            return np.full_like(amp_data, AMP_SIGMA_ABS, dtype=float)
        return np.asarray(amp_sigma, dtype=float)
    if AMP_SIGMA_MODE == "relative":
        return AMP_REL_SIGMA * np.maximum(amp_data, AMP_ABS_FLOOR)
    if AMP_SIGMA_MODE != "constant":
        raise ValueError(f"Unknown AMP_RML_AMP_SIGMA_MODE={AMP_SIGMA_MODE!r}")
    return np.full_like(amp_data, AMP_SIGMA_ABS, dtype=float)


def sigma_tag() -> str:
    if AMP_SIGMA_MODE == "physical":
        amp_fp = getattr(wt, "AMPLITUDE_MODE_FALSE_POSITIVE", getattr(aug, "MODE_FALSE_POSITIVE", 0.05))
        return f"ampphys_ampfp{amp_fp:g}"
    if AMP_SIGMA_MODE == "relative":
        return f"amprel{100.0 * AMP_REL_SIGMA:g}pct"
    return f"ampabs{AMP_SIGMA_ABS:g}"


def project_flux_positive(image: np.ndarray, smooth_pix: float = 0.0) -> np.ndarray:
    out = np.clip(image, 0.0, None)
    if smooth_pix > 0.15:
        out = np.clip(base.gaussian_filter(out, smooth_pix), 0.0, None)
    total = float(np.sum(out))
    if not np.isfinite(total) or total <= 0.0:
        out = np.ones_like(image)
        total = float(np.sum(out))
    return out / total


def fft_vis(image: np.ndarray) -> np.ndarray:
    return np.fft.fftshift(np.fft.fft2(np.fft.ifftshift(image)))


def adjoint_image(grid_gradient: np.ndarray) -> np.ndarray:
    n = grid_gradient.shape[0]
    return (n * n) * np.fft.fftshift(np.fft.ifft2(np.fft.ifftshift(grid_gradient))).real


def broad_gaussian_prior(axis_uas: np.ndarray, fwhm_uas: float = 95.0) -> np.ndarray:
    xx, yy = np.meshgrid(axis_uas, axis_uas)
    sigma = fwhm_uas / 2.355
    prior = np.exp(-0.5 * (xx * xx + yy * yy) / sigma**2)
    return project_flux_positive(prior)


def bilinear_adjoint_samples(
    grid: np.ndarray,
    uv_axis: np.ndarray,
    u: np.ndarray,
    v: np.ndarray,
    coeff: np.ndarray,
) -> None:
    """Scatter sample-space complex gradients to the FFT grid.

    This is the adjoint of ``base.interp_vis`` up to the explicit Hermitian
    completion needed for a real image.  The older scripts used nearest-cell
    scattering, which is fast but can bias sparse long-baseline gradients.
    """
    n = grid.shape[0]
    du = uv_axis[1] - uv_axis[0]

    def scatter(us: np.ndarray, vs: np.ndarray, cs: np.ndarray) -> None:
        fu = (us - uv_axis[0]) / du
        fv = (vs - uv_axis[0]) / du
        iu = np.floor(fu).astype(int)
        iv = np.floor(fv).astype(int)
        valid = (iu >= 0) & (iu < n - 1) & (iv >= 0) & (iv < n - 1) & np.isfinite(cs)
        if not np.any(valid):
            return
        iu = iu[valid]
        iv = iv[valid]
        tu = fu[valid] - iu
        tv = fv[valid] - iv
        cv = cs[valid]
        flat = grid.reshape(-1)
        for dx, dy, weight in (
            (0, 0, (1.0 - tu) * (1.0 - tv)),
            (1, 0, tu * (1.0 - tv)),
            (0, 1, (1.0 - tu) * tv),
            (1, 1, tu * tv),
        ):
            np.add.at(flat, (iv + dy) * n + (iu + dx), weight * cv)

    scatter(u, v, coeff)
    scatter(-u, -v, np.conj(coeff))


def load_maunakea_case(path: Path = MAUNAKEA_PLUS5_LAYOUT) -> aug.NetworkCase:
    payload = json.loads(path.read_text())
    telescopes = [
        aug.Telescope(
            station["name"],
            float(station["x_km"]),
            float(station["y_km"]),
            float(station["diameter_m"]),
            bool(station["is_added"]),
        )
        for station in payload["stations"]
    ]
    return aug.NetworkCase(
        key=payload.get("case_key", path.stem.replace("_layout", "")),
        title=payload.get("case_title", "Maunakea augmented array"),
        latitude_deg=19.8250,
        center_latlon=(19.8250, -155.4720),
        telescopes=telescopes,
        hub_km=tuple(payload["hub_km"]),
        optimization_score=float(payload.get("metrics", {}).get("score", 0.0)),
    )


def load_maunakea_plus3_case() -> aug.NetworkCase:
    """Top-four Maunakea telescopes plus the best three remote stations.

    The selected outstations are the 12.5, 16.25, and 20 km stations from the
    saved top4+five layout.  This keeps the earlier Hawaii+3 benchmark stable.
    """
    full = load_maunakea_case()
    core = [tel for tel in full.telescopes if not tel.is_added]
    remote = [tel for tel in full.telescopes if tel.is_added][-3:]
    return aug.NetworkCase(
        key="maunakea_top4_plus3_ngc4151",
        title="Maunakea top-four core + three remote 5 m stations",
        latitude_deg=full.latitude_deg,
        center_latlon=full.center_latlon,
        telescopes=core + remote,
        hub_km=full.hub_km,
        optimization_score=full.optimization_score,
    )


def load_optimal8_case() -> aug.NetworkCase:
    payload = json.loads(OPTIMAL8_LAYOUT.read_text())
    stations = np.asarray(payload["stations_km"], dtype=float)
    # Use the latest hub preferred in the manuscript updates.
    hub = (-2.0, -5.0)
    telescopes = [
        aug.Telescope(f"O{i + 1}", float(x), float(y), 5.0, True)
        for i, (x, y) in enumerate(stations)
    ]
    return aug.NetworkCase(
        key="optimal8_ngc4151_hub_m2_m5",
        title="Synthetic 8-station optimized topology",
        latitude_deg=19.8250,
        center_latlon=(19.8250, -155.4720),
        telescopes=telescopes,
        hub_km=hub,
        optimization_score=0.0,
    )


def simulate_case(case: aug.NetworkCase) -> tuple[list[dict[str, np.ndarray]], dict, np.ndarray, np.ndarray]:
    old = {
        "loss": aug.FIBER_LOSS_DB_PER_KM,
        "fp": getattr(aug, "BASELINE_FALSE_POSITIVE", 0.0),
        "mode_fp": getattr(aug, "MODE_FALSE_POSITIVE", 0.05),
        "pair_fp": getattr(aug, "PAIR_FALSE_POSITIVE", 0.0),
        "n_time": aug.N_TIME_WINDOWS,
        "exp": aug.EXPOSURE_S,
        "gap": aug.EXPOSURE_GAP_S,
        "wt_fp": getattr(wt, "BASELINE_FALSE_POSITIVE", 0.0),
        "wt_npix": wt.N_PIX,
        "wt_snr": wt.SNR_BOOST,
        "wt_days": wt.OBSERVING_DAYS,
    }
    aug.FIBER_LOSS_DB_PER_KM = FIBER_LOSS_DB_PER_KM
    aug.BASELINE_FALSE_POSITIVE = PAIR_FALSE_POSITIVE
    aug.MODE_FALSE_POSITIVE = MODE_FALSE_POSITIVE
    aug.PAIR_FALSE_POSITIVE = PAIR_FALSE_POSITIVE
    aug.N_TIME_WINDOWS = N_TIME_WINDOWS
    aug.EXPOSURE_S = EXPOSURE_S
    aug.EXPOSURE_GAP_S = EXPOSURE_GAP_S
    wt.BASELINE_FALSE_POSITIVE = PAIR_FALSE_POSITIVE
    wt.N_PIX = N_RML
    wt.SNR_BOOST = SNR_BOOST
    wt.OBSERVING_DAYS = OBSERVING_DAYS
    try:
        with ngc.patched_source(SOURCE):
            bands, stats, truth, axis_uas = wt.simulate_bands(case)
            stats["source_morphology"] = ngc.SOURCE_MORPHOLOGY
            return bands, stats, truth, axis_uas
    finally:
        aug.FIBER_LOSS_DB_PER_KM = old["loss"]
        aug.BASELINE_FALSE_POSITIVE = old["fp"]
        aug.MODE_FALSE_POSITIVE = old["mode_fp"]
        aug.PAIR_FALSE_POSITIVE = old["pair_fp"]
        aug.N_TIME_WINDOWS = old["n_time"]
        aug.EXPOSURE_S = old["exp"]
        aug.EXPOSURE_GAP_S = old["gap"]
        wt.BASELINE_FALSE_POSITIVE = old["wt_fp"]
        wt.N_PIX = old["wt_npix"]
        wt.SNR_BOOST = old["wt_snr"]
        wt.OBSERVING_DAYS = old["wt_days"]


def quick_dirty_start(
    bands: list[dict[str, np.ndarray]],
    strategy: str,
    truth: np.ndarray,
) -> np.ndarray:
    old_npix = wt.N_PIX
    wt.N_PIX = truth.shape[0]
    try:
        dirty, _ = latest.stack_dirty_psf(bands, strategy, truth, fill=True)
    finally:
        wt.N_PIX = old_npix
    return project_flux_positive(dirty - np.percentile(dirty, 1.0), smooth_pix=0.8)


def amp_phase_objective(
    image: np.ndarray,
    bands: list[dict[str, np.ndarray]],
    strategy: str,
    q_basis: np.ndarray,
    uv_axis: np.ndarray,
    phase_floor: float,
    n_edges: int,
) -> tuple[float, float, float]:
    vis_grid = fft_vis(image)
    amp_loss = 0.0
    phase_loss = 0.0
    n_bucket = 0
    for band in bands:
        u = band["u"]
        v = band["v"]
        model = base.interp_vis(vis_grid, uv_axis, u, v)
        amp_model = np.abs(model)
        amp_data = np.asarray(band["amp"], dtype=float)
        amp_sigma = amplitude_sigma(amp_data, band.get("amp_sigma"))
        amp_w = 1.0 / np.maximum(amp_sigma**2, 1e-12)
        amp_w /= max(float(np.nanmedian(amp_w)), 1e-30)
        amp_w = np.clip(amp_w, 0.02, 60.0)
        amp_loss += float(np.mean(amp_w * (amp_model - amp_data) ** 2))

        data = band[f"vis_{strategy}"]
        sigma = band[f"sigma_{strategy}"].reshape(-1, n_edges)
        model_phase = np.angle(model).reshape(-1, n_edges)
        data_phase = np.angle(data).reshape(-1, n_edges)
        if strategy == "all":
            resid_edge = np.angle(np.exp(1j * (model_phase - data_phase)))
            w_edge = 1.0 / np.maximum(sigma**2 + phase_floor**2, 1e-12)
            w_edge /= max(float(np.nanmedian(w_edge)), 1e-30)
            w_edge = np.clip(w_edge, 0.02, 60.0)
            phase_loss += float(np.mean(w_edge * resid_edge**2))
        else:
            model_q = model_phase @ q_basis
            data_q = data_phase @ q_basis
            resid_q = np.angle(np.exp(1j * (model_q - data_q)))
            sigma_q = band.get(f"sigmaq_{strategy}")
            if sigma_q is not None:
                coord_sigma2 = np.asarray(sigma_q, dtype=float).reshape(-1, q_basis.shape[1]) ** 2 + phase_floor**2
            else:
                coord_sigma2 = (sigma**2 + phase_floor**2) @ (q_basis**2)
            wq = 1.0 / np.maximum(coord_sigma2, 1e-12)
            wq /= max(float(np.nanmedian(wq)), 1e-30)
            wq = np.clip(wq, 0.02, 60.0)
            phase_loss += float(np.mean(wq * resid_q**2))
        n_bucket += 1
    amp_loss /= max(n_bucket, 1)
    phase_loss /= max(n_bucket, 1)
    return amp_loss + phase_loss, amp_loss, phase_loss


def amplitude_closure_rml(
    bands: list[dict[str, np.ndarray]],
    case: aug.NetworkCase,
    strategy: str,
    prior: np.ndarray,
    start: np.ndarray,
    *,
    fov_rad: float,
) -> tuple[np.ndarray, dict[str, float]]:
    stations, _, _, _ = aug.station_table_from_case(case)
    edges = base.edge_list(len(stations))
    n_edges = len(edges)
    q_basis = base.orthonormal_cycle_basis(base.root_cycle_basis(edges, len(stations)))
    uv_axis = np.fft.fftshift(np.fft.fftfreq(N_RML, d=fov_rad / N_RML))

    phase_floor = PHASE_FLOOR_RAD

    x = project_flux_positive(0.55 * start + 0.45 * prior, smooth_pix=0.25)
    history: dict[str, float] = {}
    eps = 1e-8
    for iteration in range(N_ITER):
        vis_grid = fft_vis(x)
        amp_grad_grid = np.zeros_like(vis_grid)
        phase_grad_grid = np.zeros_like(vis_grid)
        amp_loss = 0.0
        phase_loss = 0.0
        n_amp = 0
        n_phase = 0
        for band in bands:
            u = band["u"]
            v = band["v"]
            model = base.interp_vis(vis_grid, uv_axis, u, v)
            amp_model = np.abs(model)
            amp_data = np.asarray(band["amp"], dtype=float)
            amp_sigma = amplitude_sigma(amp_data, band.get("amp_sigma"))
            amp_w = 1.0 / np.maximum(amp_sigma**2, 1e-12)
            amp_w /= max(float(np.nanmedian(amp_w)), 1e-30)
            amp_w = np.clip(amp_w, 0.02, 60.0)
            amp_resid = amp_model - amp_data
            amp_coeff = amp_w * amp_resid * model / np.maximum(amp_model, eps)
            bilinear_adjoint_samples(amp_grad_grid, uv_axis, u, v, amp_coeff)
            amp_loss += float(np.mean(amp_w * amp_resid**2))
            n_amp += 1

            data = band[f"vis_{strategy}"]
            sigma = band[f"sigma_{strategy}"].reshape(-1, n_edges)
            model_phase = np.angle(model).reshape(-1, n_edges)
            data_phase = np.angle(data).reshape(-1, n_edges)
            if strategy == "all":
                resid_edge = np.angle(np.exp(1j * (model_phase - data_phase)))
                w_edge = 1.0 / np.maximum(sigma**2 + phase_floor**2, 1e-12)
                w_edge /= max(float(np.nanmedian(w_edge)), 1e-30)
                w_edge = np.clip(w_edge, 0.02, 60.0)
                phase_coeff = (w_edge * resid_edge).reshape(-1)
                phase_loss += float(np.mean(w_edge * resid_edge**2))
            else:
                model_q = model_phase @ q_basis
                data_q = data_phase @ q_basis
                resid_q = np.angle(np.exp(1j * (model_q - data_q)))
                sigma_q = band.get(f"sigmaq_{strategy}")
                if sigma_q is not None:
                    coord_sigma2 = np.asarray(sigma_q, dtype=float).reshape(-1, q_basis.shape[1]) ** 2 + phase_floor**2
                else:
                    coord_sigma2 = (sigma**2 + phase_floor**2) @ (q_basis**2)
                wq = 1.0 / np.maximum(coord_sigma2, 1e-12)
                wq /= max(float(np.nanmedian(wq)), 1e-30)
                wq = np.clip(wq, 0.02, 60.0)
                phase_coeff = ((wq * resid_q) @ q_basis.T).reshape(-1)
                phase_loss += float(np.mean(wq * resid_q**2))
            safe_model = np.where(np.abs(model) > 1e-4, model, 1e-4 + 0j)
            phase_sample_grad = 1j * phase_coeff / np.conj(safe_model)
            bilinear_adjoint_samples(phase_grad_grid, uv_axis, u, v, phase_sample_grad)
            n_phase += 1

        amp_grad = adjoint_image(amp_grad_grid)
        phase_grad = adjoint_image(phase_grad_grid)
        prior_grad = 2.0 * (x - prior)
        entropy_grad = np.log((x + 1e-12) / (prior + 1e-12))
        tv_grad = latest.tv_gradient(x)
        reg_part = (
            PRIOR_WEIGHT * normalize_grad(prior_grad)
            + ENTROPY_WEIGHT * normalize_grad(entropy_grad)
            + TV_WEIGHT * normalize_grad(tv_grad)
        )
        data_part = AMP_GRAD_WEIGHT * normalize_grad(amp_grad) + PHASE_GRAD_WEIGHT * normalize_grad(phase_grad)
        candidates = (data_part + reg_part, -data_part + reg_part)
        smooth_pix = 0.16 if (iteration + 1) % 45 == 0 else 0.0
        if LINESEARCH:
            current_obj = (amp_loss + phase_loss) / max(n_phase, 1)
            best_x = x
            best_obj = current_obj
            for direction in candidates:
                trial_step = STEP
                for _ in range(7):
                    trial = project_flux_positive(x - trial_step * direction, smooth_pix=smooth_pix)
                    trial_obj, _, _ = amp_phase_objective(
                        trial, bands, strategy, q_basis, uv_axis, phase_floor, n_edges
                    )
                    if np.isfinite(trial_obj) and trial_obj < best_obj:
                        best_x = trial
                        best_obj = trial_obj
                        break
                    trial_step *= 0.5
            x = best_x
        else:
            x = project_flux_positive(x - STEP * candidates[0], smooth_pix=smooth_pix)
        if iteration in {0, N_ITER // 2, N_ITER - 1}:
            obj, amp_obj, phase_obj = amp_phase_objective(x, bands, strategy, q_basis, uv_axis, phase_floor, n_edges)
            history[f"objective_{iteration}"] = obj
            history[f"amp_loss_{iteration}"] = amp_obj
            history[f"phase_loss_{iteration}"] = phase_obj
    return latest.normalize_stack(x), history


def radial_profile_corr(truth: np.ndarray, image: np.ndarray, axis_uas: np.ndarray) -> float:
    xx, yy = np.meshgrid(axis_uas, axis_uas)
    rr = np.sqrt(xx * xx + yy * yy)
    bins = np.linspace(0.0, np.max(np.abs(axis_uas)), 36)
    truth_n = base.normalize_for_display(truth)
    image_n = base.normalize_for_display(image)
    t_prof: list[float] = []
    i_prof: list[float] = []
    for lo, hi in zip(bins[:-1], bins[1:]):
        mask = (rr >= lo) & (rr < hi)
        if np.count_nonzero(mask) < 4:
            continue
        t_prof.append(float(np.mean(truth_n[mask])))
        i_prof.append(float(np.mean(image_n[mask])))
    if len(t_prof) < 3 or np.std(t_prof) <= 0 or np.std(i_prof) <= 0:
        return 0.0
    return float(np.corrcoef(t_prof, i_prof)[0, 1])


def metrics_for(image: np.ndarray, truth: np.ndarray, axis_uas: np.ndarray) -> dict[str, float]:
    metrics = latest.image_metrics(SOURCE, truth, image, axis_uas)
    metrics["radial_corr"] = radial_profile_corr(truth, image, axis_uas)
    return metrics


def run_case(case: aug.NetworkCase) -> dict:
    print(f"[simulate] {case.key}", flush=True)
    bands, stats, truth, axis_uas = simulate_case(case)
    fov_rad = 2.0 * wt.HALF_WIDTH_UAS * base.UAS_TO_RAD
    prior = broad_gaussian_prior(axis_uas)
    images: dict[str, np.ndarray] = {
        "truth": truth,
        "prior": latest.normalize_stack(prior),
    }
    histories: dict[str, dict[str, float]] = {}
    metrics: dict[str, dict[str, float]] = {"prior": metrics_for(images["prior"], truth, axis_uas)}
    for strategy in ("all", "split", "direct"):
        print(f"[rml] {case.key} strategy={strategy}", flush=True)
        start = quick_dirty_start(bands, strategy, truth)
        image, history = amplitude_closure_rml(bands, case, strategy, prior, start, fov_rad=fov_rad)
        key = f"{strategy}_amp_phase_rml"
        images[key] = image
        histories[key] = history
        metrics[key] = metrics_for(image, truth, axis_uas)
    stats.update(
        {
            "source": SOURCE.name,
            "method": "EHT-style amplitude-constrained RML with reliable |V| and phase/closure-phase residuals",
            "amplitude_assumption": "|V_ij| is treated as calibrated data with a constant absolute error by default, not as an unknown image prior.",
            "amp_sigma_mode": AMP_SIGMA_MODE,
            "amp_sigma_abs": AMP_SIGMA_ABS,
            "amp_rel_sigma": AMP_REL_SIGMA,
            "amp_abs_floor": AMP_ABS_FLOOR,
            "phase_floor_rad": PHASE_FLOOR_RAD,
            "n_rml": N_RML,
            "rml_iterations": N_ITER,
            "rml_step": STEP,
            "observing_days": OBSERVING_DAYS,
            "n_time_windows": N_TIME_WINDOWS,
            "exposure_s": EXPOSURE_S,
            "exposure_gap_s": EXPOSURE_GAP_S,
            "snr_boost": SNR_BOOST,
            "fiber_loss_db_per_km": FIBER_LOSS_DB_PER_KM,
            "mode_false_positive": MODE_FALSE_POSITIVE,
            "pair_false_positive": PAIR_FALSE_POSITIVE,
            "noise_model": "pure fibre attenuation plus independent mode-local false positives",
            "metrics": metrics,
            "histories": histories,
        }
    )
    return {"case": case, "stats": stats, "bands": bands, "truth": truth, "axis_uas": axis_uas, "images": images, "metrics": metrics}


def plot_summary(results: list[dict]) -> tuple[Path, Path]:
    fig, axes = plt.subplots(len(results), 4, figsize=(8.6, 2.25 * len(results)), constrained_layout=True)
    if len(results) == 1:
        axes = axes[None, :]
    plt.rcParams.update(
        {
            "font.size": 7.0,
            "axes.labelsize": 7.0,
            "axes.titlesize": 7.4,
            "xtick.labelsize": 6.1,
            "ytick.labelsize": 6.1,
        }
    )
    cols = [
        ("truth", "Input"),
        ("all_amp_phase_rml", "All vis. + drift"),
        ("split_amp_phase_rml", "Edge-first closure"),
        ("direct_amp_phase_rml", "Direct closure"),
    ]
    image_axes = []
    short_labels = {
        "maunakea_top4_plus3_ngc4151": "Hawaii+3",
        "maunakea_top4_plus5_ngc4151": "Hawaii+5",
        "optimal8_ngc4151_hub_m2_m5": "Optimized 8",
    }
    for row, result in enumerate(results):
        axis_uas = result["axis_uas"]
        extent = [axis_uas[0], axis_uas[-1], axis_uas[0], axis_uas[-1]]
        case = result["case"]
        for col, (key, title) in enumerate(cols):
            ax = axes[row, col]
            image = result["images"][key]
            ax.imshow(opt.normalize_blr_display(image), origin="lower", extent=extent, cmap="inferno")
            if key == "truth":
                ax.set_title(title)
            else:
                m = result["metrics"][key]
                ax.set_title(f"{title}\nBLR={m['blr_corr']:.2f}, rad={m['radial_corr']:.2f}")
            ax.set_xlabel(r"$\Delta\alpha$ ($\mu$as)")
            if col == 0:
                ax.set_ylabel(f"{short_labels.get(case.key, case.key)}\n" + r"$\Delta\delta$ ($\mu$as)", fontsize=7.0)
            else:
                ax.set_yticklabels([])
            image_axes.append(ax)
    cbar = fig.colorbar(
        plt.cm.ScalarMappable(norm=colors.Normalize(vmin=0.0, vmax=1.0), cmap="inferno"),
        ax=image_axes,
        fraction=0.018,
        pad=0.012,
    )
    cbar.set_label("normalized brightness", fontsize=6.6)
    fig.suptitle(
        (
            "Reliable-amplitude RML: amplitudes + closure-protected phases; "
            f"{SOURCE.name}, {OBSERVING_DAYS} d, loss {FIBER_LOSS_DB_PER_KM:g} dB/km"
        ),
        fontsize=9.6,
        weight="bold",
    )
    tag = (
        f"eht_style_amp_closure_rml_{SOURCE.key}_{OBSERVING_DAYS}d_"
        f"{N_TIME_WINDOWS}x{EXPOSURE_S/60:g}min_loss{FIBER_LOSS_DB_PER_KM:g}_{sigma_tag()}_n{N_RML}"
    ).replace(".", "p")
    png = OUTFIG / f"{tag}.png"
    pdf = OUTFIG / f"{tag}.pdf"
    fig.savefig(png, dpi=260, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    plt.close(fig)
    return pdf, png


def write_metrics(results: list[dict]) -> tuple[Path, Path]:
    rows: list[dict[str, float | str]] = []
    for result in results:
        for key, metric in result["metrics"].items():
            rows.append({"case": result["case"].key, "image": key, **metric})
    csv_path = OUTFIG / "eht_style_amp_closure_rml_metrics.csv"
    with csv_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    summary = {
        "source": SOURCE.name,
        "source_note": SOURCE.note,
        "cases": [result["stats"] for result in results],
        "metrics_csv": str(csv_path),
    }
    json_path = OUTFIG / "eht_style_amp_closure_rml_summary.json"
    json_path.write_text(json.dumps(summary, indent=2) + "\n")
    return csv_path, json_path


def main() -> None:
    cases = [load_maunakea_plus3_case(), load_maunakea_case(), load_optimal8_case()]
    results = [run_case(case) for case in cases]
    pdf, png = plot_summary(results)
    csv_path, json_path = write_metrics(results)
    print(pdf)
    print(png)
    print(csv_path)
    print(json_path)
    for result in results:
        print(result["case"].key)
        for key in ("all_amp_phase_rml", "split_amp_phase_rml", "direct_amp_phase_rml"):
            print(" ", key, result["metrics"][key])


if __name__ == "__main__":
    main()
